language: python
cache: pip
python:
- '2.7'
install: pip install -r requirements.txt
env:
  global:
  - DJANGO_SETTINGS_MODULE=rooibos_settings.test
  - PYTHONPATH=.
script: django-admin test
before_deploy:
  - VERSION=$(git describe --always)
  - NAME=rooibos-$TRAVIS_BRANCH-$VERSION-build$TRAVIS_BUILD_NUMBER
  - mkdir -p travis-build
  - echo VERSION=\"$VERSION\" > rooibos/version.py
  - git add rooibos/version.py
  - git commit -m "Update version number"
  - git archive --prefix rooibos-$VERSION/ -o travis-build/$NAME.tar.gz HEAD
  - mkdir -p travis-build-temp
  - cd travis-build-temp
  - tar xzf ../travis-build/$NAME.tar.gz
  - zip -r ../travis-build/$NAME.zip *
  - cd ..
deploy:
  provider: s3
  access_key_id: AKIAJTFTACX5PEZXKG3Q
  secret_access_key:
    secure: IXxs8Qa6K4F9HgM1VwHx4+8rnjI3+wxyuR4gB5hipbBRRsHFfrYjffo09GlD1dx1pw5XIezYzfQJlPKfYxyS2PrZOWG4p2Oo/vWLSdkSjzfv+ro1+7aAwVFem9M9YEvbOtzbp0oR7CdJsU1L8AvB4rF45EtzWSxSM0UDJhAx4krPTzn3lbhF9lkWG4vFX5AA+OINNeNvHsR4AcqFB/WT9ljG4c2qujxTbrXb7OlfWbH2V3zfPUh7a+AC0migbQj1C3mB2zl6FUQu40dzZ1f/IYr4HUxCC9U6rDoRKs9vrVXmJM00gjlw5t30vyagCZQbnoVH8ngkclz82X8l2lFB3qPLabm/Yw6l/SwsN0qPutK8teL7Rygk+asdjAHZ6mXcTBQ12FNFba6ED++7yh7u91z7cKLZhRlPnB3TrcbdKH0IgDZJVud9C/6YSqD+60C08vdaDOOCTnMXDeRfYnefwa3pIx/xNncg+eN/g0Kq0Fxw8H/dF26itZD5yws1sO4vgRtgMi4ZGXbpFOSnY9sNSm2C9S7PZYxdY10XYKUzSfqVlBpWiiurOTl7GHcMSdaCfYk4QCR34GRQbykMUNNLyVuHqppEpmdp5+hygHHrx3EiZYp7h7BnvvCX77UxnqfFEuiy1LghT7fCWRwlhb4NIvsCBIPMHfAj+skeR9hXV7U=
  bucket: vrchost-jenkins
  acl: public_read
  on:
    repo: vrchost/rooibos
    all_branches: true
  skip_cleanup: true
  local_dir: travis-build
  upload-dir: builds/$TRAVIS_BRANCH
